apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: retail-backend:latest
        imagePullPolicy: Never # Adjust if using a registry
        ports:
        - containerPort: 8080
        env:
        - name: DB_URL
          value: "jdbc:mysql://mysql:3306/customerproductmgmtdb"
        - name: DB_USERNAME
          value: "root"
        - name: DB_PASSWORD
          value: "root"
